[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#num = "0.4.1"
rand = "0.8.5"
ron = "0.8.1"
serde = { version = "1.0.193", features = ["serde_derive"] }

